#Use docker compose 1.6 or greather.
#https://docs.docker.com/compose/install/
version: '3'

services:
  postgresDb:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_MULTIPLE_DATABASES="virtualkeypad"
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - ./config/initdb/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
volumes:
  postgres_data:
