package com.rfranco.virtualkeypad.services;

import com.rfranco.virtualkeypad.autogenerated.dtos.CreateUserRequest;
import com.rfranco.virtualkeypad.autogenerated.dtos.LoginRequest;
import com.rfranco.virtualkeypad.autogenerated.dtos.LoginResponse;
import com.rfranco.virtualkeypad.configurations.VirtualKeypadConfiguration;
import com.rfranco.virtualkeypad.exceptions.*;
import com.rfranco.virtualkeypad.models.UserModel;
import com.rfranco.virtualkeypad.repositories.LoginRepository;
import com.rfranco.virtualkeypad.repositories.UserRepository;
import io.jsonwebtoken.Claims;
import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.SignatureAlgorithm;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.redis.core.RedisTemplate;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;

import java.util.Date;
import java.util.Optional;
import java.util.concurrent.TimeUnit;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import static com.rfranco.virtualkeypad.constants.Messages.*;

@Slf4j
@Service
public class LoginService {
    @Autowired
    private LoginRepository loginrepository;

    @Autowired
    private UserRepository userRepository;

    @Autowired
    private VirtualKeypadConfiguration virtualKeypadConfiguration;

    @Autowired
    private PasswordEncoder passwordEncoder;

    /*@Autowired
    private RedisTemplate<String, String> redisTemplate;

    public void addToBlacklist(String token, long expirationTime) {
        redisTemplate.opsForValue().set(token, "invalid", expirationTime, TimeUnit.MILLISECONDS);
    }

    public boolean isBlacklisted(String token) {
        return redisTemplate.hasKey(token);
    }

    public void logoutUser(LoginRequest loginrequest){
        //TODO:generar el método logout (MAS TARDE)
       /* String jwt = token.replace("Bearer ", "");
        long expiration = getExpiration(jwt); // Extrae el tiempo de expiración del token
        blacklistService.addToBlacklist(jwt, expiration);
        return ResponseEntity.ok("Logout successful");
    }

    private long getExpiration(String token) {
        Claims claims = Jwts.parser()
                .setSigningKey(this.virtualKeypadConfiguration.getSecretKey())
                .parseClaimsJws(token)
                .getBody();
        return claims.getExpiration().getTime() - System.currentTimeMillis();
    }*/

    public void registerUser(CreateUserRequest createUserRequest){
        if(createUserRequest.getUsername().isEmpty() || createUserRequest.getEmail().isEmpty() || createUserRequest.getPassword().isEmpty()){
            log.error(BAD_USER_REQUEST);
            throw new BadRequestException(BAD_USER_REQUEST);
        }
        if(this.userRepository.findByEmail(createUserRequest.getEmail()) != null){
            log.error("User with user name {} already exist in the system",createUserRequest.getUsername());
            throw new ConflictException(USER_ALREADY_EXISTS);
        }
        checkValidEmail(createUserRequest.getEmail());
        checkValidPassword(createUserRequest.getPassword());
        try {
            UserModel usermodel = UserModel.builder()
                    .userName(createUserRequest.getUsername())
                    .password(this.passwordEncoder.encode(createUserRequest.getPassword()))
                    .email(createUserRequest.getEmail())
                    .build();

            this.loginrepository.save(usermodel);
        }catch (Exception e){
            log.error("Error creating the user", e);
            throw new InternalServerException(INTERNAL_ERROR);
        }
    }

    public LoginResponse loginUser(LoginRequest loginrequest){
        Optional<UserModel> userModel = this.userRepository.findByUserName(loginrequest.getLogin());
        if(userModel.isEmpty()){
            log.error("User with login {} not found in the system",loginrequest.getLogin());
            throw new NotFoundException(USER_NOT_FOUND);
        }
        LoginResponse response = new LoginResponse();
        if(this.passwordEncoder.matches(loginrequest.getPassword(), userModel.get().getPassword())){
            try {
                response.setLogin(userModel.get().getUserName());
                response.setJwt(createJWT(userModel.get()));
                response.setId((int)userModel.get().getUserId());
                return response;
            }catch (Exception e){
                log.error("Error creating the login response", e);
                throw new InternalServerException(INTERNAL_ERROR);
            }
        }else{
            log.error(PASSWORD_INCORRECT);
            throw new UnauthorizedException(PASSWORD_INCORRECT);
        }
    }


    public String createJWT(UserModel userModel){

        String token = Jwts.builder().
                setId("userJWT")
                .setSubject(userModel.getUserName())
                .setHeaderParam("alg","HS256")
                .setHeaderParam("typ","JWT")
                .claim("userName",userModel.getUserName())
                .claim("email",userModel.getEmail())
                .setIssuedAt(new Date(System.currentTimeMillis()))
                .setExpiration(new Date(System.currentTimeMillis() + this.virtualKeypadConfiguration.getJwtExpirationInMillis()))
                .signWith(SignatureAlgorithm.HS512,
                        this.virtualKeypadConfiguration.getSecretKey().getBytes()).compact();

        return "Bearer " + token;
    }
    public void checkValidEmail(String email){

        String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";

        Pattern pattern = Pattern.compile(emailRegex);
        if (!pattern.matcher(email).matches()) {
            log.error("Provided email is not valid: {}.", email);
            throw new BadRequestException(EMAIL_INVALID);
        }
    }
    public void checkValidPassword(String password){
        if (password.length() < 8) {
            log.error("Provided password is not valid.");
            throw new BadRequestException(PASSWORD_TOO_WEAK);
        }

        String regex = "^(?=.*[0-9])(?=.*[!@#$%^&*(),.?\":{}|<>]).+$";

        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(password);

        if(!matcher.matches()){
            log.error("Provided password is not valid.");
            throw new BadRequestException(PASSWORD_TOO_WEAK);
        }
    }
}
